apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store-demo-data
  labels:
    app.kubernetes.io/part-of: kube-agent-benchmarks
    app: store-demo
spec:
  storageClassName: fast-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
