apiVersion: v1
kind: Service
metadata:
  name: store-demo
  labels:
    app.kubernetes.io/part-of: kube-agent-benchmarks
spec:
  type: ClusterIP
  selector:
    app: store-demo
  ports:
    - name: http
      port: 80
      targetPort: http
